<h1>Editor článků</h1>

<form method="post">
	<input type="hidden" name="clanky_id" value="<?= $clanek['clanky_id'] ?>" />
	<label>
		Titulek<br />
		<input type="text" name="titulek" value="<?= $clanek['titulek'] ?>" />
	</label><br />
	<label>
		URL<br />
		<input type="text" name="url" value="<?= $clanek['url'] ?>" />
	</label><br />
	<label>
		Popisek<br />
		<input type="text" name="popisek" value="<?= $clanek['popisek'] ?>" />
	</label><br />
	<label>
		Klíčová slova<br />
		<input type="text" name="klicova_slova" value="<?= $clanek['klicova_slova'] ?>" />
	</label><br />
	<label for="obsah"></label><textarea id="obsah" name="obsah"><?= $clanek['obsah'] ?></textarea>
	<input type="submit" value="Uložit článek" />
</form>

<script src="/tinymce/tinymce.min.js"></script>
<script src="/tinymce/jquery.tinymce.min.js"></script>

<script type="text/javascript">
	tinymce.init({

		selector: '#obsah', 
		language: 'cs',
		toolbar_mode: 'sliding',

		entities: '160,nbsp',
		entity_encoding: 'named',

		plugins: [
			"advlist autolink lists link image charmap print preview anchor",	
			"searchreplace visualblocks code fullscreen",	
			"insertdatetime media table contextmenu paste"
		],

		toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
	});
</script>